- hosts: localhost
  gather_facts: false
  vars:
    # TODO: get this from an environment variable, most likely
    scoreboard_server: http://localhost:8080
  tasks:
  
  # TODO: setup rosa and aws credentials  

  - name: Get cluster list
    shell: >
      rosa list clusters -o yaml
    register: _cluster_list

  - name: Set cluster info
    set_fact:
      cluster_info: "{{ _cluster_list.stdout | from_yaml | json_query('[0]') }}"

  - name: Get cluster name
    set_fact:
      cluster_name: "{{ cluster_info.name }}"
      cluster_state: " {{ cluster_info.state }}"

  # TODO: Get actual progress statuses

  - name: Post progress report
    uri:
      url: "{{ scoreboard_server }}/progress-reports"
      method: PUT
      body:
        attendeeName: catherine
        statuses:
        - success
        - success
        - success
        - success
        - pending
      body_format: json
      status_code: 204

