- hosts: localhost
  gather_facts: false
  vars:
    # TODO: get this from an environment variable, most likely
    scoreboard_server: http://localhost:8080
  tasks:
  - name: Include Cluster Deployment Tasks
    include_tasks: deploy_cluster.yml

  - name: Include App Deployment Tasks
    include_tasks: deploy_app.yml

  - name: Post progress report
    uri:
      url: "{{ scoreboard_server }}/progress-reports"
      method: PUT
      body:
        attendeeName: andy
        clusterTasks: "{{ cluster_tasks }}"
        appTasks: "{{ app_tasks }}"
      body_format: json
      status_code: 204
